/**
 * @epoch/epoch-sdk: browser-safe TypeScript client for the Epoch Anchor program, on @solana/web3.js v1 only (no Anchor
 * runtime, no Node built-ins; `TransactionInstruction.data` uses web3.js's own Buffer class).
 * PDAs, account and event decoders, instruction builders, the error table and exact mirrors of the program's math.
 * Every function that touches an address takes `programId` explicitly.
 */

// Seeds, constants, enums
export {
  ADVANCE_STATES,
  type AdvanceState,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  BUYBACK_VENUES,
  type BuybackVenue,
  COMMISSION_KIND,
  CP_AMM_POSITION_NFT_ACCOUNT_SEED,
  INSTRUCTIONS_SYSVAR_ID,
  METEORA,
  NATIVE_MINT,
  POSITION_STATUSES,
  type PositionStatus,
  PROGRAM_CONSTANTS,
  RAW_SHARES_PER_UI_SHARE,
  rawSharesToUi,
  REVENUE_TOKEN_FLAGS,
  REVENUE_TOKEN_STATUSES,
  type RevenueTokenStatus,
  SEEDS,
  sharePriceE9ToSol,
  type Side,
  SIDES,
  TOKEN_2022_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
  type Tranche,
  TRANCHES,
  TREASURY_CLAIM_KINDS,
  type TreasuryClaimKind,
  VOTE_PROGRAM_ID,
} from './constants';

// Discriminators
export {
  ACCOUNT_DISCRIMINATORS,
  ACCOUNT_NAMES,
  type AccountName,
  accountNameOf,
  EVENT_DISCRIMINATORS,
  EVENT_NAMES,
  type EventName,
  eventNameOf,
  INSTRUCTION_DISCRIMINATORS,
  INSTRUCTION_NAMES,
  type InstructionName,
  instructionNameOf,
} from './discriminators';

// PDAs
export {
  findAdvancePda,
  findAssociatedTokenAddress,
  findBuybackEscrowPda,
  findBuybackTokensPda,
  findBuybackWsolPda,
  findDammPositionNftAccount,
  findDammPositionPda,
  findEscrowPda,
  findFeeIndexPda,
  findLenderPda,
  findPartnerTreasuryPda,
  findPoolPda,
  findPositionPda,
  findQuotePda,
  findRevenueTokenPda,
  findSwapPda,
  findTreasuryTokensAddress,
  findTreasuryWsolPda,
  findVaultPda,
  findVoteAuthPda,
  findWithdrawRequestPda,
} from './pda';

// Accounts
export {
  ACCOUNT_SIZES,
  accountFilters,
  type AdvanceAccount,
  decodeAccount,
  type DecodedAccount,
  decodeAdvance,
  decodeFeeIndex,
  decodeFeeQuote,
  decodeLenderShares,
  decodePool,
  decodeRevenueToken,
  decodeSwapPosition,
  decodeValidatorPosition,
  decodeWithdrawRequest,
  type EpochAccountMap,
  type FeeIndexAccount,
  feeIndexHistory,
  feeIndexValueFor,
  type FeeQuoteAccount,
  FIELD_OFFSETS,
  fieldFilter,
  type IndexPoint,
  type LenderSharesAccount,
  type PoolAccount,
  type PoolParams,
  revenueHistory,
  type RevenueTokenAccount,
  revenueTokenBuybacksPaused,
  revenueTokenInTerm,
  revenueTokenRedeemOpen,
  revenueTokenTermActive,
  type SwapPositionAccount,
  trailingRevenue,
  type ValidatorPositionAccount,
  type WithdrawRequestAccount,
} from './accounts';

// Events
export {
  decodeEvent,
  type EpochEvent,
  type EpochEventJson,
  type EpochEventMap,
  eventToJson,
  parseEventsFromLogs,
} from './events';

// Instructions
export {
  accrue,
  type AccrueInput,
  type BondInput,
  type BuybackParams,
  type BuybackVenueKeys,
  burnLeftover,
  type BurnLeftoverInput,
  cancelWithdraw,
  type CancelWithdrawInput,
  claimPartnerMigrationFee,
  type ClaimPartnerQuoteInput,
  claimPartnerSurplus,
  claimPartnerTradingFee,
  type ClaimPartnerTradingFeeInput,
  claimTreasuryLpFee,
  type ClaimTreasuryLpFeeInput,
  closeRevenueToken,
  type CloseRevenueTokenInput,
  configureIndex,
  type ConfigureIndexInput,
  configureRevenueToken,
  type ConfigureRevenueTokenInput,
  deposit,
  type DbcClaimPoolKeys,
  type DepositInput,
  executeBuyback,
  type ExecuteBuybackInput,
  finalizeIndex,
  type FinalizeIndexInput,
  findMeteoraVaultPda,
  initializeIndex,
  type InitializeIndexInput,
  initializePool,
  type InitializePoolInput,
  lamportsToSolString,
  markDefault,
  type MarkDefaultInput,
  onboardValidator,
  type OnboardValidatorInput,
  onboardWithBond,
  type OnboardWithBondInput,
  openSwap,
  type OpenSwapInput,
  openSwaps,
  type OpenSwapsInput,
  postBond,
  postIndex,
  type PostIndexInput,
  postQuote,
  type PostQuoteInput,
  processWithdrawal,
  type ProcessWithdrawalInput,
  redeem,
  type RedeemInput,
  registerRevenueToken,
  type RegisterRevenueTokenInput,
  releaseValidator,
  type ReleaseValidatorInput,
  requestAdvance,
  type RequestAdvanceInput,
  requestWithdraw,
  type RequestWithdrawInput,
  type ScoreUpdate,
  setCollectors,
  type SetCollectorsInput,
  setPaused,
  type SetPausedInput,
  setRoles,
  type SetRolesInput,
  settleSwap,
  type SettleSwapInput,
  solToLamports,
  sweep,
  type SweepInput,
  type SwapLeg,
  sweepPosition,
  type SweepPositionInput,
  syncRevenueTokenPool,
  type SyncRevenueTokenPoolInput,
  updateCommission,
  type UpdateCommissionInput,
  updateIdentity,
  type UpdateIdentityInput,
  updateParams,
  type UpdateParamsInput,
  updateScore,
  type UpdateScoreInput,
  vetoIndex,
  type VetoIndexInput,
  withdrawBond,
  withdrawQuote,
  type WithdrawQuoteInput,
} from './instructions';

// Errors
export { EPOCH_ERRORS, epochErrorFromCode, type EpochErrorInfo, parseEpochError } from './errors';

// Math
export {
  absorbLoss,
  assetsToShares,
  attributeRepayment,
  bpsOf,
  bpsOfCeil,
  type BuybackSkipReason,
  type BuybackSliceInput,
  type BuybackSlicePlan,
  type BuybackVenueState,
  type BuyFill,
  computeScore,
  creditLimit,
  type CreditLimitInput,
  type CurvePoint,
  dammCompoundingBuy,
  dammCompoundingMaxQuoteIn,
  dammConcentratedBuy,
  dammConcentratedMaxQuoteIn,
  dbcBuy,
  dbcLeftover,
  dbcMaxQuoteIn,
  dbcPartnerMigrationFee,
  dbcPartnerPart,
  dbcPartnerSurplus,
  deltaBase,
  deltaQuote,
  distributeIncome,
  EpochMathError,
  impactTargetSqrtPrice,
  juniorRatioBps,
  minOutFloor,
  mulDiv,
  nextSqrtFromQuoteIn,
  planBuybackSlice,
  redeemPayout,
  type ScoreInput,
  sharePriceE9,
  type ShareSplit,
  sharesToAssets,
  sliceBudget,
  sliceDueSlot,
  type SliceTiming,
  sliceTiming,
  splitSweep,
  splitSweepWithShare,
  swapCollateral,
  takerPnl,
} from './math';

// Encodings
export { base58Decode, base58Encode, base64Decode, base64Encode, bytesToHex, hexToBytes } from './encoding';
