/**
 * @epoch/epoch-sdk: browser-safe TypeScript client for the Epoch Anchor program, on @solana/web3.js v1 only (no Anchor
 * runtime, no Node built-ins; `TransactionInstruction.data` uses web3.js's own Buffer class).
 * PDAs, account and event decoders, instruction builders, the error table and exact mirrors of the program's math.
 * Every function that touches an address takes `programId` explicitly.
 */

// Seeds, constants, enums
export {
  ADVANCE_STATES,
  type AdvanceState,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  BUYBACK_VENUES,
  type BuybackVenue,
  COMMISSION_KIND,
  CP_AMM_POSITION_NFT_ACCOUNT_SEED,
  INSTRUCTIONS_SYSVAR_ID,
  JITO,
  METEORA,
  NATIVE_MINT,
  POSITION_STATUSES,
  type PositionStatus,
  PROGRAM_CONSTANTS,
  RAW_SHARES_PER_UI_SHARE,
  rawSharesToUi,
  REVENUE_TOKEN_FLAGS,
  REVENUE_TOKEN_STATUSES,
  type RevenueTokenStatus,
  SEEDS,
  sharePriceE9ToSol,
  type Side,
  SIDES,
  TOKEN_2022_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
  type Tranche,
  TRANCHES,
  TREASURY_CLAIM_KINDS,
  type TreasuryClaimKind,
  VOTE_PROGRAM_ID,
} from './constants';

// Discriminators
export {
  ACCOUNT_DISCRIMINATORS,
  ACCOUNT_NAMES,
  type AccountName,
  accountNameOf,
  EVENT_DISCRIMINATORS,
  EVENT_NAMES,
  type EventName,
  eventNameOf,
  INSTRUCTION_DISCRIMINATORS,
  INSTRUCTION_NAMES,
  type InstructionName,
  instructionNameOf,
} from './discriminators';

// PDAs
export {
  findAdvancePda,
  findAssociatedTokenAddress,
  findBuybackEscrowPda,
  findBuybackTokensPda,
  findBuybackWsolPda,
  findDammPositionNftAccount,
  findDammPositionPda,
  findDbcPoolPda,
  findEscrowPda,
  findFeeIndexPda,
  findIndexBallotPda,
  findIndexOperatorsPda,
  findLenderPda,
  findPartnerTreasuryPda,
  findPoolPda,
  findPositionPda,
  findPriorityFeeDistributionPda,
  findQuotePda,
  findRevenueTokenPda,
  findScoreConfigPda,
  findSwapPda,
  findTipDistributionPda,
  findTreasuryTokensAddress,
  findTreasuryWsolPda,
  findValidatorHistoryPda,
  findVaultPda,
  findVoteAuthPda,
  findWithdrawRequestPda,
} from './pda';

// Accounts
export {
  ACCOUNT_SIZES,
  accountFilters,
  type AdvanceAccount,
  decodeAccount,
  decodeAdvance,
  type DecodedAccount,
  decodeFeeIndex,
  activeIndexOperators,
  ballotVotes,
  decodeIndexBallot,
  decodeIndexOperators,
  decodeFeeQuote,
  decodeLenderShares,
  decodePool,
  decodeRevenueToken,
  decodeScoreConfig,
  decodeSwapPosition,
  decodeValidatorHistory,
  decodeValidatorPosition,
  decodeWithdrawRequest,
  type EpochAccountMap,
  type FeeIndexAccount,
  type IndexBallotAccount,
  type IndexBallotStatus,
  indexBallotStatus,
  type IndexOperator,
  type IndexOperatorsAccount,
  type IndexVote,
  feeIndexHistory,
  feeIndexValueFor,
  type FeeQuoteAccount,
  FIELD_OFFSETS,
  fieldFilter,
  HISTORY_SCORE_FLAGS,
  HISTORY_SOURCES,
  type HistoryEntry,
  type IndexPoint,
  type LenderSharesAccount,
  type PoolAccount,
  type PoolParams,
  revenueHistory,
  type RevenueTokenAccount,
  revenueTokenBuybacksPaused,
  revenueTokenCloseMode,
  revenueTokenInTerm,
  revenueTokenMaxImpactBound,
  revenueTokenRedeemOpen,
  revenueTokenTermActive,
  type ScoreConfigAccount,
  type SwapPositionAccount,
  trailingRevenue,
  type ValidatorHistoryAccount,
  type ValidatorPositionAccount,
  type WithdrawRequestAccount,
} from './accounts';

// Events
export {
  decodeEvent,
  type EpochEvent,
  type EpochEventJson,
  type EventJsonScalar,
  type EventJsonValue,
  type EpochEventMap,
  eventToJson,
  parseEventsFromLogs,
} from './events';

// Instructions
export {
  accrue,
  type AccrueInput,
  type BondInput,
  burnLeftover,
  type BurnLeftoverInput,
  type BuybackParams,
  type BuybackVenueKeys,
  cancelWithdraw,
  type CancelWithdrawInput,
  claimPartnerMigrationFee,
  type ClaimPartnerQuoteInput,
  claimPartnerSurplus,
  claimPartnerTradingFee,
  type ClaimPartnerTradingFeeInput,
  claimTreasuryLpFee,
  type ClaimTreasuryLpFeeInput,
  closeRevenueToken,
  type CloseRevenueTokenInput,
  configureIndex,
  type ConfigureIndexInput,
  configureRevenueToken,
  type ConfigureRevenueTokenInput,
  configureScoring,
  type ConfigureScoringInput,
  type CopyDistributionInput,
  copyPriorityFeeDistribution,
  copyTipDistributionAccount,
  copyVoteAccount,
  type DbcClaimPoolKeys,
  DEFAULT_SCORING_PARAMS,
  deposit,
  type DepositInput,
  executeBuyback,
  type ExecuteBuybackInput,
  finalizeIndex,
  type FinalizeIndexInput,
  findMeteoraVaultPda,
  hedgeSwapAccounts,
  type HistoryInput,
  initializeIndex,
  type InitializeIndexInput,
  initializePool,
  type InitializePoolInput,
  initValidatorHistory,
  lamportsToSolString,
  markDefault,
  type MarkDefaultInput,
  onboardValidator,
  type OnboardValidatorInput,
  onboardWithBond,
  type OnboardWithBondInput,
  openSwap,
  type OpenSwapInput,
  openSwaps,
  type OpenSwapsInput,
  postBond,
  postIndex,
  type PostIndexInput,
  postQuote,
  type PostQuoteInput,
  processWithdrawal,
  type ProcessWithdrawalInput,
  redeem,
  type RedeemInput,
  refreshScore,
  type RefreshScoreInput,
  registerRevenueToken,
  type RegisterRevenueTokenInput,
  releaseValidator,
  type ReleaseValidatorInput,
  requestAdvance,
  type RequestAdvanceInput,
  requestWithdraw,
  type RequestWithdrawInput,
  type ScoreUpdate,
  type ScoringParams,
  setCollectors,
  type SetCollectorsInput,
  setPaused,
  type SetPausedInput,
  setRoles,
  type SetRolesInput,
  settleSwap,
  type SettleSwapInput,
  solToLamports,
  type StakeInfo,
  type SwapLeg,
  sweep,
  type SweepInput,
  sweepPosition,
  type SweepPositionInput,
  syncRevenueTokenPool,
  type SyncRevenueTokenPoolInput,
  updateCommission,
  type UpdateCommissionInput,
  updateIdentity,
  type UpdateIdentityInput,
  updateParams,
  type UpdateParamsInput,
  updateScore,
  type UpdateScoreInput,
  updateStakeInfo,
  type UpdateStakeInfoInput,
  vetoIndex,
  type VetoIndexInput,
  initializeIndexOperators,
  type InitializeIndexOperatorsInput,
  addIndexOperator,
  removeIndexOperator,
  setIndexOperatorWeight,
  type IndexOperatorInput,
  type IndexOperatorWeightInput,
  setIndexConsensus,
  type SetIndexConsensusInput,
  castIndexVote,
  type CastIndexVoteInput,
  submitIndexBallot,
  resetIndexBallot,
  type IndexBallotInput,
  closeIndexBallot,
  type CloseIndexBallotInput,
  withdrawBond,
  withdrawQuote,
  type WithdrawQuoteInput,
} from './instructions';

// Errors
export { EPOCH_ERRORS, epochErrorFromCode, type EpochErrorInfo, parseEpochError } from './errors';

// Math
export {
  absorbLoss,
  agreesWithin,
  assetsToShares,
  attributeRepayment,
  bpsOf,
  bpsOfCeil,
  type BuybackSkipReason,
  type BuybackSliceInput,
  type BuybackSlicePlan,
  type BuybackVenueState,
  type BuyFill,
  circulatingSupply,
  computeScore,
  type ConsensusTally,
  creditLimit,
  type CreditLimitInput,
  type CurvePoint,
  dammCompoundingBuy,
  dammCompoundingMaxQuoteIn,
  dammConcentratedBuy,
  dammConcentratedMaxQuoteIn,
  dbcBuy,
  dbcLeftover,
  dbcMaxQuoteIn,
  dbcMigratedFeeBps,
  dbcMinBaseFeeNumerator,
  dbcPartnerMigrationFee,
  dbcPartnerPart,
  dbcPartnerSurplus,
  deltaBase,
  deltaQuote,
  deviationBps,
  distributeIncome,
  EpochMathError,
  FEE_NUMERATOR_PER_BPS,
  impactTargetSqrtPrice,
  juniorRatioBps,
  maxImpactBound,
  meetsThreshold,
  minOutFloor,
  mulDiv,
  nextSqrtFromQuoteIn,
  planBuybackSlice,
  redeemPayout,
  type ScoreInput,
  sharePriceE9,
  type ShareSplit,
  sharesToAssets,
  sliceBudget,
  sliceDueSlot,
  type SliceTiming,
  sliceTiming,
  splitSweep,
  splitSweepWithShare,
  swapCollateral,
  takerPnl,
  tallyVotes,
  venueFeeFloorBps,
  weightedMedian,
  type WeightedVote,
} from './math';

// DBC launch configs: register_revenue_token's checks, for a pre-flight
export {
  checkLaunchConfig,
  DBC_POOL_CONFIG_DISCRIMINATOR,
  DBC_POOL_CONFIG_LEN,
  DBC_VIRTUAL_POOL_DISCRIMINATOR,
  DBC_VIRTUAL_POOL_LEN,
  type DbcLaunchConfig,
  type DbcPoolHead,
  decodeDbcLaunchConfig,
  decodeDbcPoolHead,
  type LaunchConfigCheck,
  type LaunchConfigError,
} from './launchConfig';

// Encodings
export { base58Decode, base58Encode, base64Decode, base64Encode, bytesToHex, hexToBytes } from './encoding';
