/** Country names as Stakewiz reports them (IP geolocation) → ISO 3166-1 alpha-2, for `?country=DE,US`. */
const CODES: Record<string, string> = {
  Argentina: 'AR',
  Australia: 'AU',
  Austria: 'AT',
  Belgium: 'BE',
  Brazil: 'BR',
  Bulgaria: 'BG',
  Canada: 'CA',
  'Cayman Islands': 'KY',
  Chile: 'CL',
  China: 'CN',
  Croatia: 'HR',
  Cyprus: 'CY',
  Czechia: 'CZ',
  'Czech Republic': 'CZ',
  Denmark: 'DK',
  Estonia: 'EE',
  Finland: 'FI',
  France: 'FR',
  Georgia: 'GE',
  Germany: 'DE',
  Greece: 'GR',
  'Hong Kong': 'HK',
  Hungary: 'HU',
  Iceland: 'IS',
  India: 'IN',
  Indonesia: 'ID',
  Ireland: 'IE',
  Israel: 'IL',
  Italy: 'IT',
  Japan: 'JP',
  Kazakhstan: 'KZ',
  Latvia: 'LV',
  Lithuania: 'LT',
  'Republic of Lithuania': 'LT',
  Luxembourg: 'LU',
  Malaysia: 'MY',
  Malta: 'MT',
  Mexico: 'MX',
  Moldova: 'MD',
  Netherlands: 'NL',
  'The Netherlands': 'NL',
  'New Zealand': 'NZ',
  Norway: 'NO',
  Poland: 'PL',
  Portugal: 'PT',
  Romania: 'RO',
  'Russian Federation': 'RU',
  Russia: 'RU',
  Serbia: 'RS',
  Singapore: 'SG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  'South Africa': 'ZA',
  'South Korea': 'KR',
  'Korea, Republic of': 'KR',
  Spain: 'ES',
  Sweden: 'SE',
  Switzerland: 'CH',
  Taiwan: 'TW',
  Thailand: 'TH',
  Turkey: 'TR',
  Türkiye: 'TR',
  Ukraine: 'UA',
  'United Arab Emirates': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
  Vietnam: 'VN',
};

/** ISO code for a country name, or `XX` when unknown. */
export const countryCode = (name: string | null | undefined): string => (name ? (CODES[name] ?? 'XX') : 'XX');
