import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3100',{waitUntil:'networkidle'});
await page.getByRole('button',{name:'Pause animations'}).click();
assert.equal(await page.locator('.landing-page').getAttribute('data-paused'),'true');
await page.locator('.stream-field').waitFor();
await page.locator('.audience-section').scrollIntoViewIfNeeded();
await page.waitForTimeout(200);
assert.equal(await page.locator('.audience-section').evaluate(el=>getComputedStyle(el).opacity),'1');
await page.getByRole('button',{name:'For validators',exact:true}).click();
await page.waitForTimeout(800);
await page.locator('.audience-section').screenshot({path:'design/screens/impl/epoch-paper-operators.png'});
await page.getByRole('button',{name:'Resume animations'}).click();
await page.locator('.audience-section').scrollIntoViewIfNeeded();
await page.waitForTimeout(1200);
const canvas=page.locator('.visual-paper canvas');
const a=await canvas.screenshot();await page.waitForTimeout(350);const b=await canvas.screenshot();assert.equal(a.equals(b),false,'Paper visibly animates');
await page.getByRole('button',{name:'Pause animations'}).click();
await page.locator('.audience-section').scrollIntoViewIfNeeded();await page.waitForTimeout(300);
const c=await canvas.screenshot();await page.waitForTimeout(350);const d=await canvas.screenshot();assert.equal(c.equals(d),true,'Paper stops when paused');
await page.locator('.launch-closing').scrollIntoViewIfNeeded();await page.locator('.launch-closing').screenshot({path:'design/screens/impl/epoch-laser-closing.png'});
assert.deepEqual(errors,[]);console.log('PASS: global pause, visible paused content, paper animation/pause pixel comparison, scene renders without errors.');await browser.close();
