import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.EPOCH_APP_URL||'http://localhost:3100';
await page.goto(base+'/terminal');
await page.getByRole('heading',{name:'Terminal',exact:true}).waitFor();
await page.getByRole('tab',{name:'Arriving',exact:true}).click();
await page.getByRole('heading',{name:/Stake arriving/}).waitFor();
await page.waitForURL(/flow=arriving/);
await page.getByRole('button',{name:'64 epochs',exact:true}).click();
await page.waitForURL(/range=64/);
await page.getByRole('button',{name:'What is the Fee Index?',exact:true}).click();
await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Got it'}).click();
await page.goto(base+'/validators');
await page.getByLabel('Search validators',{exact:true}).fill('NTT');
await page.getByRole('link',{name:/NTT DOCOMO GLOBAL/}).waitFor();
await page.waitForURL(/q=NTT/);await page.reload();
await page.getByLabel('Search validators',{exact:true}).waitFor();
assert.equal(await page.getByLabel('Search validators',{exact:true}).inputValue(),'NTT');
await page.getByLabel('Search validators',{exact:true}).fill('');
await page.getByRole('button',{name:'Watch Figment',exact:true}).click();
await page.getByRole('tab',{name:/Watchlist/}).click();
await page.getByRole('link',{name:/Figment/}).waitFor();
await page.getByRole('tab',{name:'All validators',exact:true}).click();
await page.getByRole('checkbox',{name:'Compare Figment',exact:true}).first().check();
await page.getByRole('checkbox',{name:'Compare Helius',exact:true}).first().check();
await page.getByRole('button',{name:'Compare side by side'}).click();
await page.getByRole('heading',{name:'Compare validators',exact:true}).waitFor();
await page.keyboard.press('Escape');
await page.goto(base+'/vault');
await page.getByRole('button',{name:'Deposit',exact:true}).click();
await page.getByRole('heading',{name:'Deposit into the Vault'}).waitFor();
await page.getByLabel('Deposit amount · SOL').fill('25');
await page.getByRole('checkbox',{name:'I understand the deposit risks'}).check();
assert.match(await page.getByRole('dialog').innerText(),/sample figures/);
await page.keyboard.press('Escape');
await page.getByRole('tab',{name:'Protection',exact:true}).click();
await page.locator('#loss').fill('100');
await page.getByText('Senior loss',{exact:true}).waitFor();
await page.goto(base+'/me');
await page.getByLabel('Solana wallet address',{exact:true}).fill('invalid');
await page.getByRole('button',{name:'View address',exact:true}).click();
await page.getByText('Enter a valid Solana wallet address.',{exact:true}).waitFor();
await page.getByRole('button',{name:'Explore a labelled demo wallet'}).click();
await page.getByRole('heading',{name:'Your stake, at a glance'}).waitFor();
assert.match(await page.locator('main').innerText(),/balances are invented/);
await page.goto(base+'/');
await page.getByRole('button',{name:'Does my staked SOL move into the vault?'}).click();
await page.getByText('No. Your native stake stays',{exact:false}).waitFor();
await page.getByRole('link',{name:'Open the Terminal'}).click();
await page.getByRole('heading',{name:'Terminal',exact:true}).waitFor();
assert.deepEqual(errors,[]);
console.log('PASS: chart controls, URL persistence, search, watchlist, comparison, deposit preview, stress controls, address validation, demo mode, FAQ and navigation.');
await browser.close();
